version: '3'
services:
  core:
    volumes:
      - ./digitalbits-core-pubnet.cfg:/digitalbits-core.cfg
  frontier:
    environment:
      - HISTORY_ARCHIVE_URLS=https://history.digitalbits.org/prd/core-live/core_live_001
      - NETWORK_PASSPHRASE=Public Global DigitalBits Network ; September 2015
