# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install deps
        run: sudo apt update && sudo apt install -y unzip curl

      - name: Install Golang
        run: |
          wget https://dl.google.com/go/go1.15.2.linux-amd64.tar.gz 
          sudo tar -xvf go1.15.2.linux-amd64.tar.gz   
          sudo mv go /usr/local  

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Build the app    
        run: |
          sudo mkdir -p /go/src/github.com/digitalbits/go

          export GOPATH=/go
          export GO111MODULE=on

          sudo cp -Rf ./* $GOPATH/
          sudo go install github.com/digitalbits/go/services/...

      - name: Release
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }}
          export AWS_DEFAULT_REGION=eu-central-1

          aws s3 sync /go/bin/ s3://digitalbits-bin/services/
